#555 added nanosecond to GTimeStamp and DateUtility
cristal-ise/cristal-ise pull request #556
Opened 2022-01-17 05:37 UTC by Jerichol-titusgt

Fixes #555

2022-01-17 22:28 UTC, taurus227 requested changes

2022-01-17 22:28 UTC, taurus227 commented on kernel/src/main/java/org/cristalise/kernel/utils/DateUtility.java
>                      Integer.parseInt(time.substring(17,19)),
how do you store nanoseconds on 3 digits? these would be milliseconds, right?

2022-01-19 16:01 UTC, kovax requested changes
Make sure all related classes changed, so find references of GTimeStamp in the code. For example 
please change GTimeStampComparator as well.

2022-01-21 02:15 UTC, taurus227 approved these changes

2022-02-19 05:12 UTC, taurus227 approved these changes

2022-02-19 11:40 UTC, kovax approved these changes

2022-02-19 18:01 UTC, merged